### PR TITLE
Created Challenge page

### PR DESCRIPTION
**Pull request by dennohpeter**
- Created Challenge page with some code-lab cards and drop-down to select challenge category

- Added bulma css
codelabs

### CODE REVIEW

**Review by jackline-kaunda — APPROVED** [review]

**Review by jackline-kaunda — CHANGES_REQUESTED** [review]
can we test what ever is being render to the view?

**Review by midigofrank — APPROVED** [review]

**Comment by dennohpeter** [comment]
> can we test what ever is being render to the view?

sure!!!

**Review by jackline-kaunda — APPROVED** [review]

**Review by okothkongo — APPROVED** [review]

**Review by TraceyOnim — COMMENTED** [review]
for 'start' i would suggest a button for it

**Comment by Infinical** [comment]
Search catalog seems much of a search field rather than a drop-down button

**Comment by dennohpeter** [comment]
> Search catalog seems much of a search field rather than a drop-down button

image

**Pull request merged**
